<?php
/**
 *
 *
 *
 */

class VT_UrlToMedia_FeaturedImage extends VT_UrlToMedia
{

    function __construct( $post, $url , $details )
    {
        parent::__construct($post, $url, $meta_key = '' , $details );
    }

    function start_url_to_media()
    {
        $check = parent::start_url_to_media(); // TODO: Change the autogenerated stub

        if ( ! $check )
            return;

        if ( ! has_post_thumbnail( $this->post_id ) )
        {
            $error = set_post_thumbnail($this->post_id ,$this->attachment_id );
            if ( $error === false )
            {
                $this->writeLog( 'ERROR : impossible set post thumbnail for post id : ' .  $this->post_id );
            }
        }
        else
        {
            $this->writeLog( 'ERROR : post thumbnail already set on post id : ' .  $this->post_id );
        }

    }


}
